# Generated by Django 3.2 on 2023-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
